version: '3'
services:
  nginx:
    image: nginx
    ports:
    - 80:80
    volumes:
    - $DOCKER_V_PATH/nginx/Apps:/data
    - $DOCKER_V_PATH/nginx/conf.d:/etc/nginx/conf.d
    - $DOCKER_V_PATH/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
