version: '3.4'
services:
  #    nginx:
  #      image: nginx:1.13.6-alpine
  #      hostname: nginx
  #      ports:
  #        - 80:80/tcp
  #      networks:
  #        wordpress:
  #          aliases:
  #            - nginx
  #      volumes:
  #        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #        - ./www:/var/www/html:rw
  #        - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
  #      logging:
  #        driver: json-file
  #        options:
  #          max-file: '3'
  #          max-size: 100m
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - 80:80
    #    hostname: php
    #    networks:
    #      wordpress:
    #        aliases:
    #          - wordpress
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=jeffrey
      - WORDPRESS_DB_NAME=WordPress
      - WORDPRESS_TABLE_PREFIX=wp_
  #    volumes:
  #      - ./www:/var/www/html:rw
  #      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
  #      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
  #    logging:
  #      driver: json-file
  #      options:
  #        max-file: '3'
  #        max-size: 100m
  mysql:
    env_file:
      - mysql.env
    image: mysql:5.6
    volumes:
      - $DOCKER_V_PATH/wordpress/mysql/data:/var/lib/mysql

#    redis:
#      image: redis:4.0.6
#      hostname: redis
#      networks:
#        wordpress:
#          aliases:
#            - redis
#      volumes:
#        - ./redis:/data:rw
#        - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
#      logging:
#        driver: json-file
#        options:
#          max-file: '3'
#          max-size: 100m
#  networks:
#    wordpress:
#      external: true
